export const DaicoAddress = "0x000000000033e92DB97B4B3beCD2c255126C60aC";

export const DaicoAbi = [
  { inputs: [], stateMutability: "payable", type: "constructor" },
  { inputs: [], name: "BadLPBps", type: "error" },
  { inputs: [], name: "Expired", type: "error" },
  { inputs: [], name: "InvalidParams", type: "error" },
  { inputs: [], name: "NoSale", type: "error" },
  { inputs: [], name: "NoTap", type: "error" },
  { inputs: [], name: "NothingToClaim", type: "error" },
  { inputs: [], name: "SlippageExceeded", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "dao",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "tribTkn",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "lpBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeOrHook",
        type: "uint256",
      },
    ],
    name: "LPConfigSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "dao",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "tribTkn",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tribUsed",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "forTknUsed",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
    ],
    name: "LPInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "dao",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "tribTkn",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "payAmt",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "forTkn",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "buyAmt",
        type: "uint256",
      },
    ],
    name: "SaleBought",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "dao",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "tribTkn",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tribAmt",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "forTkn",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "forAmt",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint40",
        name: "deadline",
        type: "uint40",
      },
    ],
    name: "SaleSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "dao",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "ops",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tribTkn",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "TapClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "dao",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "oldOps",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOps",
        type: "address",
      },
    ],
    name: "TapOpsUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "dao",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "oldRate",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "newRate",
        type: "uint128",
      },
    ],
    name: "TapRateUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "dao",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "ops",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "tribTkn",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "ratePerSec",
        type: "uint128",
      },
    ],
    name: "TapSet",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "dao", type: "address" },
      { internalType: "address", name: "tribTkn", type: "address" },
      { internalType: "uint256", name: "payAmt", type: "uint256" },
      { internalType: "uint256", name: "minBuyAmt", type: "uint256" },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "dao", type: "address" },
      { internalType: "address", name: "tribTkn", type: "address" },
      { internalType: "uint256", name: "buyAmt", type: "uint256" },
      { internalType: "uint256", name: "maxPayAmt", type: "uint256" },
    ],
    name: "buyExactOut",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "dao", type: "address" }],
    name: "claimTap",
    outputs: [{ internalType: "uint256", name: "claimed", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "dao", type: "address" }],
    name: "claimableTap",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "dao", type: "address" },
      { internalType: "address", name: "tribTkn", type: "address" },
    ],
    name: "lpConfigs",
    outputs: [
      { internalType: "uint16", name: "lpBps", type: "uint16" },
      { internalType: "uint16", name: "maxSlipBps", type: "uint16" },
      { internalType: "uint256", name: "feeOrHook", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "dao", type: "address" }],
    name: "pendingTap",
    outputs: [{ internalType: "uint256", name: "owed", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "dao", type: "address" },
      { internalType: "address", name: "tribTkn", type: "address" },
      { internalType: "uint256", name: "payAmt", type: "uint256" },
    ],
    name: "quoteBuy",
    outputs: [{ internalType: "uint256", name: "buyAmt", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "dao", type: "address" },
      { internalType: "address", name: "tribTkn", type: "address" },
      { internalType: "uint256", name: "buyAmt", type: "uint256" },
    ],
    name: "quotePayExactOut",
    outputs: [{ internalType: "uint256", name: "payAmt", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "dao", type: "address" },
      { internalType: "address", name: "tribTkn", type: "address" },
    ],
    name: "sales",
    outputs: [
      { internalType: "uint256", name: "tribAmt", type: "uint256" },
      { internalType: "uint256", name: "forAmt", type: "uint256" },
      { internalType: "address", name: "forTkn", type: "address" },
      { internalType: "uint40", name: "deadline", type: "uint40" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "tribTkn", type: "address" },
      { internalType: "uint16", name: "lpBps", type: "uint16" },
      { internalType: "uint16", name: "maxSlipBps", type: "uint16" },
      { internalType: "uint256", name: "feeOrHook", type: "uint256" },
    ],
    name: "setLPConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "tribTkn", type: "address" },
      { internalType: "uint256", name: "tribAmt", type: "uint256" },
      { internalType: "address", name: "forTkn", type: "address" },
      { internalType: "uint256", name: "forAmt", type: "uint256" },
      { internalType: "uint40", name: "deadline", type: "uint40" },
    ],
    name: "setSale",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "tribTkn", type: "address" },
      { internalType: "uint256", name: "tribAmt", type: "uint256" },
      { internalType: "address", name: "forTkn", type: "address" },
      { internalType: "uint256", name: "forAmt", type: "uint256" },
      { internalType: "uint40", name: "deadline", type: "uint40" },
      { internalType: "uint16", name: "lpBps", type: "uint16" },
      { internalType: "uint16", name: "maxSlipBps", type: "uint16" },
      { internalType: "uint256", name: "feeOrHook", type: "uint256" },
    ],
    name: "setSaleWithLP",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "tribTkn", type: "address" },
      { internalType: "uint256", name: "tribAmt", type: "uint256" },
      { internalType: "address", name: "forTkn", type: "address" },
      { internalType: "uint256", name: "forAmt", type: "uint256" },
      { internalType: "uint40", name: "deadline", type: "uint40" },
      { internalType: "uint16", name: "lpBps", type: "uint16" },
      { internalType: "uint16", name: "maxSlipBps", type: "uint16" },
      { internalType: "uint256", name: "feeOrHook", type: "uint256" },
      { internalType: "address", name: "ops", type: "address" },
      { internalType: "uint128", name: "ratePerSec", type: "uint128" },
    ],
    name: "setSaleWithLPAndTap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "tribTkn", type: "address" },
      { internalType: "uint256", name: "tribAmt", type: "uint256" },
      { internalType: "address", name: "forTkn", type: "address" },
      { internalType: "uint256", name: "forAmt", type: "uint256" },
      { internalType: "uint40", name: "deadline", type: "uint40" },
      { internalType: "address", name: "ops", type: "address" },
      { internalType: "uint128", name: "ratePerSec", type: "uint128" },
    ],
    name: "setSaleWithTap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOps", type: "address" }],
    name: "setTapOps",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint128", name: "newRate", type: "uint128" }],
    name: "setTapRate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "dao", type: "address" },
      { internalType: "address", name: "forTkn", type: "address" },
      {
        components: [
          {
            internalType: "address",
            name: "tribTkn",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tribAmt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "saleSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "forAmt",
            type: "uint256",
          },
          {
            internalType: "uint40",
            name: "deadline",
            type: "uint40",
          },
          { internalType: "bool", name: "sellLoot", type: "bool" },
          { internalType: "uint16", name: "lpBps", type: "uint16" },
          {
            internalType: "uint16",
            name: "maxSlipBps",
            type: "uint16",
          },
          {
            internalType: "uint256",
            name: "feeOrHook",
            type: "uint256",
          },
        ],
        internalType: "struct DAICO.DAICOConfig",
        name: "daicoConfig",
        type: "tuple",
      },
      {
        components: [
          { internalType: "address", name: "ops", type: "address" },
          {
            internalType: "uint128",
            name: "ratePerSec",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "tapAllowance",
            type: "uint256",
          },
        ],
        internalType: "struct DAICO.TapConfig",
        name: "tapConfig",
        type: "tuple",
      },
    ],
    name: "setupDAICO",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "summoner",
            type: "address",
          },
          {
            internalType: "address",
            name: "molochImpl",
            type: "address",
          },
          {
            internalType: "address",
            name: "sharesImpl",
            type: "address",
          },
          {
            internalType: "address",
            name: "lootImpl",
            type: "address",
          },
        ],
        internalType: "struct DAICO.SummonConfig",
        name: "summonConfig",
        type: "tuple",
      },
      { internalType: "string", name: "orgName", type: "string" },
      { internalType: "string", name: "orgSymbol", type: "string" },
      { internalType: "string", name: "orgURI", type: "string" },
      { internalType: "uint16", name: "quorumBps", type: "uint16" },
      { internalType: "bool", name: "ragequittable", type: "bool" },
      { internalType: "address", name: "renderer", type: "address" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      {
        internalType: "address[]",
        name: "initHolders",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "initShares",
        type: "uint256[]",
      },
      { internalType: "bool", name: "sharesLocked", type: "bool" },
      { internalType: "bool", name: "lootLocked", type: "bool" },
      {
        components: [
          {
            internalType: "address",
            name: "tribTkn",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tribAmt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "saleSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "forAmt",
            type: "uint256",
          },
          {
            internalType: "uint40",
            name: "deadline",
            type: "uint40",
          },
          { internalType: "bool", name: "sellLoot", type: "bool" },
          { internalType: "uint16", name: "lpBps", type: "uint16" },
          {
            internalType: "uint16",
            name: "maxSlipBps",
            type: "uint16",
          },
          {
            internalType: "uint256",
            name: "feeOrHook",
            type: "uint256",
          },
        ],
        internalType: "struct DAICO.DAICOConfig",
        name: "daicoConfig",
        type: "tuple",
      },
    ],
    name: "summonDAICO",
    outputs: [{ internalType: "address", name: "dao", type: "address" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "summoner",
            type: "address",
          },
          {
            internalType: "address",
            name: "molochImpl",
            type: "address",
          },
          {
            internalType: "address",
            name: "sharesImpl",
            type: "address",
          },
          {
            internalType: "address",
            name: "lootImpl",
            type: "address",
          },
        ],
        internalType: "struct DAICO.SummonConfig",
        name: "summonConfig",
        type: "tuple",
      },
      { internalType: "string", name: "orgName", type: "string" },
      { internalType: "string", name: "orgSymbol", type: "string" },
      { internalType: "string", name: "orgURI", type: "string" },
      { internalType: "uint16", name: "quorumBps", type: "uint16" },
      { internalType: "bool", name: "ragequittable", type: "bool" },
      { internalType: "address", name: "renderer", type: "address" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      {
        internalType: "address[]",
        name: "initHolders",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "initShares",
        type: "uint256[]",
      },
      { internalType: "bool", name: "sharesLocked", type: "bool" },
      { internalType: "bool", name: "lootLocked", type: "bool" },
      {
        components: [
          {
            internalType: "address",
            name: "tribTkn",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tribAmt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "saleSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "forAmt",
            type: "uint256",
          },
          {
            internalType: "uint40",
            name: "deadline",
            type: "uint40",
          },
          { internalType: "bool", name: "sellLoot", type: "bool" },
          { internalType: "uint16", name: "lpBps", type: "uint16" },
          {
            internalType: "uint16",
            name: "maxSlipBps",
            type: "uint16",
          },
          {
            internalType: "uint256",
            name: "feeOrHook",
            type: "uint256",
          },
        ],
        internalType: "struct DAICO.DAICOConfig",
        name: "daicoConfig",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "target",
            type: "address",
          },
          { internalType: "uint256", name: "value", type: "uint256" },
          { internalType: "bytes", name: "data", type: "bytes" },
        ],
        internalType: "struct Call[]",
        name: "customCalls",
        type: "tuple[]",
      },
    ],
    name: "summonDAICOCustom",
    outputs: [{ internalType: "address", name: "dao", type: "address" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "summoner",
            type: "address",
          },
          {
            internalType: "address",
            name: "molochImpl",
            type: "address",
          },
          {
            internalType: "address",
            name: "sharesImpl",
            type: "address",
          },
          {
            internalType: "address",
            name: "lootImpl",
            type: "address",
          },
        ],
        internalType: "struct DAICO.SummonConfig",
        name: "summonConfig",
        type: "tuple",
      },
      { internalType: "string", name: "orgName", type: "string" },
      { internalType: "string", name: "orgSymbol", type: "string" },
      { internalType: "string", name: "orgURI", type: "string" },
      { internalType: "uint16", name: "quorumBps", type: "uint16" },
      { internalType: "bool", name: "ragequittable", type: "bool" },
      { internalType: "address", name: "renderer", type: "address" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      {
        internalType: "address[]",
        name: "initHolders",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "initShares",
        type: "uint256[]",
      },
      { internalType: "bool", name: "sharesLocked", type: "bool" },
      { internalType: "bool", name: "lootLocked", type: "bool" },
      {
        components: [
          {
            internalType: "address",
            name: "tribTkn",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tribAmt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "saleSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "forAmt",
            type: "uint256",
          },
          {
            internalType: "uint40",
            name: "deadline",
            type: "uint40",
          },
          { internalType: "bool", name: "sellLoot", type: "bool" },
          { internalType: "uint16", name: "lpBps", type: "uint16" },
          {
            internalType: "uint16",
            name: "maxSlipBps",
            type: "uint16",
          },
          {
            internalType: "uint256",
            name: "feeOrHook",
            type: "uint256",
          },
        ],
        internalType: "struct DAICO.DAICOConfig",
        name: "daicoConfig",
        type: "tuple",
      },
      {
        components: [
          { internalType: "address", name: "ops", type: "address" },
          {
            internalType: "uint128",
            name: "ratePerSec",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "tapAllowance",
            type: "uint256",
          },
        ],
        internalType: "struct DAICO.TapConfig",
        name: "tapConfig",
        type: "tuple",
      },
    ],
    name: "summonDAICOWithTap",
    outputs: [{ internalType: "address", name: "dao", type: "address" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "summoner",
            type: "address",
          },
          {
            internalType: "address",
            name: "molochImpl",
            type: "address",
          },
          {
            internalType: "address",
            name: "sharesImpl",
            type: "address",
          },
          {
            internalType: "address",
            name: "lootImpl",
            type: "address",
          },
        ],
        internalType: "struct DAICO.SummonConfig",
        name: "summonConfig",
        type: "tuple",
      },
      { internalType: "string", name: "orgName", type: "string" },
      { internalType: "string", name: "orgSymbol", type: "string" },
      { internalType: "string", name: "orgURI", type: "string" },
      { internalType: "uint16", name: "quorumBps", type: "uint16" },
      { internalType: "bool", name: "ragequittable", type: "bool" },
      { internalType: "address", name: "renderer", type: "address" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      {
        internalType: "address[]",
        name: "initHolders",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "initShares",
        type: "uint256[]",
      },
      { internalType: "bool", name: "sharesLocked", type: "bool" },
      { internalType: "bool", name: "lootLocked", type: "bool" },
      {
        components: [
          {
            internalType: "address",
            name: "tribTkn",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tribAmt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "saleSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "forAmt",
            type: "uint256",
          },
          {
            internalType: "uint40",
            name: "deadline",
            type: "uint40",
          },
          { internalType: "bool", name: "sellLoot", type: "bool" },
          { internalType: "uint16", name: "lpBps", type: "uint16" },
          {
            internalType: "uint16",
            name: "maxSlipBps",
            type: "uint16",
          },
          {
            internalType: "uint256",
            name: "feeOrHook",
            type: "uint256",
          },
        ],
        internalType: "struct DAICO.DAICOConfig",
        name: "daicoConfig",
        type: "tuple",
      },
      {
        components: [
          { internalType: "address", name: "ops", type: "address" },
          {
            internalType: "uint128",
            name: "ratePerSec",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "tapAllowance",
            type: "uint256",
          },
        ],
        internalType: "struct DAICO.TapConfig",
        name: "tapConfig",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "target",
            type: "address",
          },
          { internalType: "uint256", name: "value", type: "uint256" },
          { internalType: "bytes", name: "data", type: "bytes" },
        ],
        internalType: "struct Call[]",
        name: "customCalls",
        type: "tuple[]",
      },
    ],
    name: "summonDAICOWithTapCustom",
    outputs: [{ internalType: "address", name: "dao", type: "address" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "dao", type: "address" }],
    name: "taps",
    outputs: [
      { internalType: "address", name: "ops", type: "address" },
      { internalType: "address", name: "tribTkn", type: "address" },
      { internalType: "uint128", name: "ratePerSec", type: "uint128" },
      { internalType: "uint64", name: "lastClaim", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
