export const ZChefAddress = "0x000000000077A1C8f192b94145C2D94E68d752bf";
export const ZChefAbi = [
  { inputs: [], stateMutability: "payable", type: "constructor" },
  { inputs: [], name: "AddLiquidityFail", type: "error" },
  { inputs: [], name: "Exists", type: "error" },
  { inputs: [], name: "InvalidDuration", type: "error" },
  { inputs: [], name: "InvalidPoolKey", type: "error" },
  { inputs: [], name: "LPMismatch", type: "error" },
  { inputs: [], name: "NoPool", type: "error" },
  { inputs: [], name: "NoStake", type: "error" },
  { inputs: [], name: "NothingToSweep", type: "error" },
  { inputs: [], name: "Overflow", type: "error" },
  { inputs: [], name: "PrecisionOverflow", type: "error" },
  { inputs: [], name: "Reentrancy", type: "error" },
  { inputs: [], name: "SamePool", type: "error" },
  { inputs: [], name: "StakeRemaining", type: "error" },
  { inputs: [], name: "StreamActive", type: "error" },
  { inputs: [], name: "StreamEnded", type: "error" },
  { inputs: [], name: "SwapExactInFail", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  { inputs: [], name: "TransferFromFailed", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  { inputs: [], name: "ZeroAmount", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "uint256", name: "chefId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "uint256", name: "chefId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "shares", type: "uint256" },
    ],
    name: "EmergencyWithdraw",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "creator", type: "address" },
      { indexed: true, internalType: "uint256", name: "chefId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "uint64", name: "duration", type: "uint64" },
    ],
    name: "StreamCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "chefId", type: "uint256" },
      { indexed: false, internalType: "uint64", name: "oldEnd", type: "uint64" },
      { indexed: false, internalType: "uint64", name: "newEnd", type: "uint64" },
    ],
    name: "StreamExtended",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "chefId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "Sweep",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "caller", type: "address" },
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "uint256", name: "chefId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "shares", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "pending", type: "uint256" },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "lpToken", type: "address" },
      { internalType: "uint256", name: "lpId", type: "uint256" },
      { internalType: "address", name: "rewardToken", type: "address" },
      { internalType: "uint256", name: "rewardId", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint64", name: "duration", type: "uint64" },
      { internalType: "bytes32", name: "uniqueBytes", type: "bytes32" },
    ],
    name: "createStream",
    outputs: [{ internalType: "uint256", name: "chefId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "chefId", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "chefId", type: "uint256" }],
    name: "emergencyWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "chefId", type: "uint256" }],
    name: "harvest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "fromChefId", type: "uint256" },
      { internalType: "uint256", name: "toChefId", type: "uint256" },
      { internalType: "uint256", name: "shares", type: "uint256" },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "chefId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "pendingReward",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "chefId", type: "uint256" }],
    name: "pools",
    outputs: [
      { internalType: "address", name: "lpToken", type: "address" },
      { internalType: "uint256", name: "lpId", type: "uint256" },
      { internalType: "address", name: "rewardToken", type: "address" },
      { internalType: "uint256", name: "rewardId", type: "uint256" },
      { internalType: "uint128", name: "rewardRate", type: "uint128" },
      { internalType: "uint64", name: "end", type: "uint64" },
      { internalType: "uint64", name: "lastUpdate", type: "uint64" },
      { internalType: "uint128", name: "totalShares", type: "uint128" },
      { internalType: "uint256", name: "accRewardPerShare", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "chefId", type: "uint256" }],
    name: "rewardPerSharePerYear",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "chefId", type: "uint256" }],
    name: "rewardPerShareRemaining",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "chefId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "rewardPerYear",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "chefId", type: "uint256" }],
    name: "streamCreator",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "chefId", type: "uint256" },
      { internalType: "address", name: "to", type: "address" },
    ],
    name: "sweepRemainder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "chefId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "userDebt",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "chefId", type: "uint256" },
      { internalType: "uint256", name: "shares", type: "uint256" },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "lpSrc", type: "address" },
      { internalType: "uint256", name: "chefId", type: "uint256" },
      {
        components: [
          { internalType: "uint256", name: "id0", type: "uint256" },
          { internalType: "uint256", name: "id1", type: "uint256" },
          { internalType: "address", name: "token0", type: "address" },
          { internalType: "address", name: "token1", type: "address" },
          { internalType: "uint256", name: "feeOrHook", type: "uint256" },
        ],
        internalType: "struct PoolKey",
        name: "poolKey",
        type: "tuple",
      },
      { internalType: "uint256", name: "amountOutMin", type: "uint256" },
      { internalType: "uint256", name: "amount0Min", type: "uint256" },
      { internalType: "uint256", name: "amount1Min", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    name: "zapDeposit",
    outputs: [
      { internalType: "uint256", name: "amount0", type: "uint256" },
      { internalType: "uint256", name: "amount1", type: "uint256" },
      { internalType: "uint256", name: "liquidity", type: "uint256" },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;
