export const zICOAbi = [
  { inputs: [], stateMutability: "payable", type: "constructor" },
  { inputs: [], name: "BadLPBps", type: "error" },
  { inputs: [], name: "Max96", type: "error" },
  { inputs: [], name: "NoStake", type: "error" },
  { inputs: [], name: "NotZ", type: "error" },
  { inputs: [], name: "Reentrancy", type: "error" },
  { inputs: [], name: "SlipBps", type: "error" },
  { inputs: [], name: "StakeLocked", type: "error" },
  { inputs: [], name: "ZeroId", type: "error" },
  { inputs: [], name: "ZeroOut", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "id0", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "id1", type: "uint256" },
      {
        indexed: true,
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeOrHook",
        type: "uint256",
      },
    ],
    name: "CreatePool",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "coinId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "orderHash",
        type: "bytes32",
      },
    ],
    name: "MakeOrder",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "coinId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint96",
        name: "ethRate",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "chefId",
        type: "uint256",
      },
    ],
    name: "OTC",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint256", name: "chefId", type: "uint256" }],
    name: "accX12",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "coinId", type: "uint256" },
      { internalType: "uint256", name: "maxSlippageBps", type: "uint256" },
    ],
    name: "buyOTC",
    outputs: [{ internalType: "uint256", name: "quoteOut", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "uint96", name: "ethRate", type: "uint96" },
      { internalType: "uint16", name: "lpBps", type: "uint16" },
      { internalType: "uint256", name: "otcSupply", type: "uint256" },
      { internalType: "uint256", name: "creatorSupply", type: "uint256" },
      { internalType: "uint256", name: "creatorUnlock", type: "uint256" },
      { internalType: "uint256", name: "airdropIncentive", type: "uint256" },
      { internalType: "uint256", name: "airdropIncentiveId", type: "uint256" },
      { internalType: "uint256", name: "airdropPriceX18", type: "uint256" },
      { internalType: "string", name: "uri", type: "string" },
    ],
    name: "createCoinWithOTC",
    outputs: [{ internalType: "uint256", name: "coinId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "uint96", name: "ethRate", type: "uint96" },
      { internalType: "uint16", name: "lpBps", type: "uint16" },
      { internalType: "uint256", name: "otcSupply", type: "uint256" },
      { internalType: "uint256", name: "feeOrHook", type: "uint256" },
      { internalType: "uint256", name: "creatorSupply", type: "uint256" },
      { internalType: "uint256", name: "creatorUnlock", type: "uint256" },
      { internalType: "uint256", name: "incentiveAmount", type: "uint256" },
      { internalType: "uint64", name: "incentiveDuration", type: "uint64" },
      { internalType: "uint256", name: "airdropIncentive", type: "uint256" },
      { internalType: "uint256", name: "airdropIncentiveId", type: "uint256" },
      { internalType: "uint256", name: "airdropPriceX18", type: "uint256" },
      { internalType: "string", name: "uri", type: "string" },
    ],
    name: "createCoinWithOTCAndIncentive",
    outputs: [
      { internalType: "uint256", name: "coinId", type: "uint256" },
      { internalType: "uint256", name: "chefId", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bool", name: "lpLock", type: "bool" },
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "address", name: "tokenIn", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "uint256", name: "amountIn", type: "uint256" },
      { internalType: "uint256", name: "feeOrHook", type: "uint256" },
      { internalType: "uint256", name: "poolSupply", type: "uint256" },
      { internalType: "uint256", name: "creatorSupply", type: "uint256" },
      { internalType: "uint256", name: "creatorUnlock", type: "uint256" },
      { internalType: "uint256", name: "incentiveAmount", type: "uint256" },
      { internalType: "uint64", name: "incentiveDuration", type: "uint64" },
      { internalType: "uint256", name: "airdropIncentive", type: "uint256" },
      { internalType: "uint256", name: "airdropIncentiveId", type: "uint256" },
      { internalType: "uint256", name: "airdropPriceX18", type: "uint256" },
      { internalType: "string", name: "uri", type: "string" },
    ],
    name: "createCoinWithPool",
    outputs: [
      { internalType: "uint256", name: "coinId", type: "uint256" },
      { internalType: "uint256", name: "lp", type: "uint256" },
      { internalType: "uint256", name: "chefId", type: "uint256" },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "tokenIn", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "uint256", name: "amountIn", type: "uint256" },
      { internalType: "uint256", name: "feeOrHook", type: "uint256" },
      { internalType: "uint256", name: "poolSupply", type: "uint256" },
      { internalType: "uint256", name: "creatorSupply", type: "uint256" },
      { internalType: "string", name: "uri", type: "string" },
    ],
    name: "createCoinWithPoolSimple",
    outputs: [
      { internalType: "uint256", name: "coinId", type: "uint256" },
      { internalType: "uint256", name: "lp", type: "uint256" },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "chefId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "debt",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "chefId", type: "uint256" }],
    name: "harvest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "coinId", type: "uint256" }],
    name: "otcStatus",
    outputs: [
      {
        components: [
          { internalType: "address", name: "creator", type: "address" },
          { internalType: "uint96", name: "ethRate", type: "uint96" },
          { internalType: "uint16", name: "lpBps", type: "uint16" },
          { internalType: "uint256", name: "chefId", type: "uint256" },
          { internalType: "uint256", name: "feeOrHook", type: "uint256" },
          { internalType: "uint256", name: "zicoInventory", type: "uint256" },
          { internalType: "uint256", name: "poolId", type: "uint256" },
          { internalType: "uint256", name: "reserveEth", type: "uint256" },
          { internalType: "uint256", name: "reserveCoin", type: "uint256" },
          { internalType: "uint256", name: "coinsPerEthX18", type: "uint256" },
          { internalType: "uint256", name: "ethPerCoinX18", type: "uint256" },
        ],
        internalType: "struct zICO.OTCStatus",
        name: "s",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "coinId", type: "uint256" }],
    name: "otcs",
    outputs: [
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "uint96", name: "ethRate", type: "uint96" },
      { internalType: "uint16", name: "lpBps", type: "uint16" },
      { internalType: "uint256", name: "chefId", type: "uint256" },
      { internalType: "uint256", name: "feeOrHook", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "chefId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "stake",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "chefId", type: "uint256" },
      { internalType: "uint256", name: "shares", type: "uint256" },
    ],
    name: "withdrawAfterIncentive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;

export const zICOAddress = "0x000000000069aa14fb673a86952eb0785f38911c";
