/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WlfiRouteImport } from './routes/wlfi'
import { Route as UserRouteImport } from './routes/user'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as SendRouteImport } from './routes/send'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as OneshotRouteImport } from './routes/oneshot'
import { Route as LimitRouteImport } from './routes/limit'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as FarmRouteImport } from './routes/farm'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EnsRouteImport } from './routes/ens'
import { Route as CultRouteImport } from './routes/cult'
import { Route as CoinpaperRouteImport } from './routes/coinpaper'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PositionsIndexRouteImport } from './routes/positions/index'
import { Route as FarmIndexRouteImport } from './routes/farm/index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as PositionsCreateRouteImport } from './routes/positions/create'
import { Route as FarmCreateRouteImport } from './routes/farm/create'
import { Route as ExploreTokensRouteImport } from './routes/explore/tokens'
import { Route as ExplorePoolsRouteImport } from './routes/explore/pools'
import { Route as ExploreOrdersRouteImport } from './routes/explore/orders'
import { Route as ExploreBondedCoinsRouteImport } from './routes/explore/bonded-coins'
import { Route as CCoinIdRouteImport } from './routes/c.$coinId'

const WlfiRoute = WlfiRouteImport.update({
  id: '/wlfi',
  path: '/wlfi',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const OneshotRoute = OneshotRouteImport.update({
  id: '/oneshot',
  path: '/oneshot',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitRoute = LimitRouteImport.update({
  id: '/limit',
  path: '/limit',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmRoute = FarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsRoute = EnsRouteImport.update({
  id: '/ens',
  path: '/ens',
  getParentRoute: () => rootRouteImport,
} as any)
const CultRoute = CultRouteImport.update({
  id: '/cult',
  path: '/cult',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinpaperRoute = CoinpaperRouteImport.update({
  id: '/coinpaper',
  path: '/coinpaper',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsIndexRoute = PositionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PositionsRoute,
} as any)
const FarmIndexRoute = FarmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmRoute,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsCreateRoute = PositionsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PositionsRoute,
} as any)
const FarmCreateRoute = FarmCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => FarmRoute,
} as any)
const ExploreTokensRoute = ExploreTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => ExploreRoute,
} as any)
const ExplorePoolsRoute = ExplorePoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreOrdersRoute = ExploreOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreBondedCoinsRoute = ExploreBondedCoinsRouteImport.update({
  id: '/bonded-coins',
  path: '/bonded-coins',
  getParentRoute: () => ExploreRoute,
} as any)
const CCoinIdRoute = CCoinIdRouteImport.update({
  id: '/c/$coinId',
  path: '/c/$coinId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coinpaper': typeof CoinpaperRoute
  '/cult': typeof CultRoute
  '/ens': typeof EnsRoute
  '/explore': typeof ExploreRouteWithChildren
  '/farm': typeof FarmRouteWithChildren
  '/launch': typeof LaunchRoute
  '/limit': typeof LimitRoute
  '/oneshot': typeof OneshotRoute
  '/positions': typeof PositionsRouteWithChildren
  '/send': typeof SendRoute
  '/swap': typeof SwapRoute
  '/user': typeof UserRoute
  '/wlfi': typeof WlfiRoute
  '/c/$coinId': typeof CCoinIdRoute
  '/explore/bonded-coins': typeof ExploreBondedCoinsRoute
  '/explore/orders': typeof ExploreOrdersRoute
  '/explore/pools': typeof ExplorePoolsRoute
  '/explore/tokens': typeof ExploreTokensRoute
  '/farm/create': typeof FarmCreateRoute
  '/positions/create': typeof PositionsCreateRoute
  '/u/$userId': typeof UUserIdRoute
  '/farm/': typeof FarmIndexRoute
  '/positions/': typeof PositionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coinpaper': typeof CoinpaperRoute
  '/cult': typeof CultRoute
  '/ens': typeof EnsRoute
  '/explore': typeof ExploreRouteWithChildren
  '/launch': typeof LaunchRoute
  '/limit': typeof LimitRoute
  '/oneshot': typeof OneshotRoute
  '/send': typeof SendRoute
  '/swap': typeof SwapRoute
  '/user': typeof UserRoute
  '/wlfi': typeof WlfiRoute
  '/c/$coinId': typeof CCoinIdRoute
  '/explore/bonded-coins': typeof ExploreBondedCoinsRoute
  '/explore/orders': typeof ExploreOrdersRoute
  '/explore/pools': typeof ExplorePoolsRoute
  '/explore/tokens': typeof ExploreTokensRoute
  '/farm/create': typeof FarmCreateRoute
  '/positions/create': typeof PositionsCreateRoute
  '/u/$userId': typeof UUserIdRoute
  '/farm': typeof FarmIndexRoute
  '/positions': typeof PositionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coinpaper': typeof CoinpaperRoute
  '/cult': typeof CultRoute
  '/ens': typeof EnsRoute
  '/explore': typeof ExploreRouteWithChildren
  '/farm': typeof FarmRouteWithChildren
  '/launch': typeof LaunchRoute
  '/limit': typeof LimitRoute
  '/oneshot': typeof OneshotRoute
  '/positions': typeof PositionsRouteWithChildren
  '/send': typeof SendRoute
  '/swap': typeof SwapRoute
  '/user': typeof UserRoute
  '/wlfi': typeof WlfiRoute
  '/c/$coinId': typeof CCoinIdRoute
  '/explore/bonded-coins': typeof ExploreBondedCoinsRoute
  '/explore/orders': typeof ExploreOrdersRoute
  '/explore/pools': typeof ExplorePoolsRoute
  '/explore/tokens': typeof ExploreTokensRoute
  '/farm/create': typeof FarmCreateRoute
  '/positions/create': typeof PositionsCreateRoute
  '/u/$userId': typeof UUserIdRoute
  '/farm/': typeof FarmIndexRoute
  '/positions/': typeof PositionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coinpaper'
    | '/cult'
    | '/ens'
    | '/explore'
    | '/farm'
    | '/launch'
    | '/limit'
    | '/oneshot'
    | '/positions'
    | '/send'
    | '/swap'
    | '/user'
    | '/wlfi'
    | '/c/$coinId'
    | '/explore/bonded-coins'
    | '/explore/orders'
    | '/explore/pools'
    | '/explore/tokens'
    | '/farm/create'
    | '/positions/create'
    | '/u/$userId'
    | '/farm/'
    | '/positions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coinpaper'
    | '/cult'
    | '/ens'
    | '/explore'
    | '/launch'
    | '/limit'
    | '/oneshot'
    | '/send'
    | '/swap'
    | '/user'
    | '/wlfi'
    | '/c/$coinId'
    | '/explore/bonded-coins'
    | '/explore/orders'
    | '/explore/pools'
    | '/explore/tokens'
    | '/farm/create'
    | '/positions/create'
    | '/u/$userId'
    | '/farm'
    | '/positions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coinpaper'
    | '/cult'
    | '/ens'
    | '/explore'
    | '/farm'
    | '/launch'
    | '/limit'
    | '/oneshot'
    | '/positions'
    | '/send'
    | '/swap'
    | '/user'
    | '/wlfi'
    | '/c/$coinId'
    | '/explore/bonded-coins'
    | '/explore/orders'
    | '/explore/pools'
    | '/explore/tokens'
    | '/farm/create'
    | '/positions/create'
    | '/u/$userId'
    | '/farm/'
    | '/positions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoinpaperRoute: typeof CoinpaperRoute
  CultRoute: typeof CultRoute
  EnsRoute: typeof EnsRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  FarmRoute: typeof FarmRouteWithChildren
  LaunchRoute: typeof LaunchRoute
  LimitRoute: typeof LimitRoute
  OneshotRoute: typeof OneshotRoute
  PositionsRoute: typeof PositionsRouteWithChildren
  SendRoute: typeof SendRoute
  SwapRoute: typeof SwapRoute
  UserRoute: typeof UserRoute
  WlfiRoute: typeof WlfiRoute
  CCoinIdRoute: typeof CCoinIdRoute
  UUserIdRoute: typeof UUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wlfi': {
      id: '/wlfi'
      path: '/wlfi'
      fullPath: '/wlfi'
      preLoaderRoute: typeof WlfiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oneshot': {
      id: '/oneshot'
      path: '/oneshot'
      fullPath: '/oneshot'
      preLoaderRoute: typeof OneshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limit': {
      id: '/limit'
      path: '/limit'
      fullPath: '/limit'
      preLoaderRoute: typeof LimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm': {
      id: '/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ens': {
      id: '/ens'
      path: '/ens'
      fullPath: '/ens'
      preLoaderRoute: typeof EnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cult': {
      id: '/cult'
      path: '/cult'
      fullPath: '/cult'
      preLoaderRoute: typeof CultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coinpaper': {
      id: '/coinpaper'
      path: '/coinpaper'
      fullPath: '/coinpaper'
      preLoaderRoute: typeof CoinpaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions/': {
      id: '/positions/'
      path: '/'
      fullPath: '/positions/'
      preLoaderRoute: typeof PositionsIndexRouteImport
      parentRoute: typeof PositionsRoute
    }
    '/farm/': {
      id: '/farm/'
      path: '/'
      fullPath: '/farm/'
      preLoaderRoute: typeof FarmIndexRouteImport
      parentRoute: typeof FarmRoute
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions/create': {
      id: '/positions/create'
      path: '/create'
      fullPath: '/positions/create'
      preLoaderRoute: typeof PositionsCreateRouteImport
      parentRoute: typeof PositionsRoute
    }
    '/farm/create': {
      id: '/farm/create'
      path: '/create'
      fullPath: '/farm/create'
      preLoaderRoute: typeof FarmCreateRouteImport
      parentRoute: typeof FarmRoute
    }
    '/explore/tokens': {
      id: '/explore/tokens'
      path: '/tokens'
      fullPath: '/explore/tokens'
      preLoaderRoute: typeof ExploreTokensRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/pools': {
      id: '/explore/pools'
      path: '/pools'
      fullPath: '/explore/pools'
      preLoaderRoute: typeof ExplorePoolsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/orders': {
      id: '/explore/orders'
      path: '/orders'
      fullPath: '/explore/orders'
      preLoaderRoute: typeof ExploreOrdersRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/bonded-coins': {
      id: '/explore/bonded-coins'
      path: '/bonded-coins'
      fullPath: '/explore/bonded-coins'
      preLoaderRoute: typeof ExploreBondedCoinsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/c/$coinId': {
      id: '/c/$coinId'
      path: '/c/$coinId'
      fullPath: '/c/$coinId'
      preLoaderRoute: typeof CCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExploreRouteChildren {
  ExploreBondedCoinsRoute: typeof ExploreBondedCoinsRoute
  ExploreOrdersRoute: typeof ExploreOrdersRoute
  ExplorePoolsRoute: typeof ExplorePoolsRoute
  ExploreTokensRoute: typeof ExploreTokensRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreBondedCoinsRoute: ExploreBondedCoinsRoute,
  ExploreOrdersRoute: ExploreOrdersRoute,
  ExplorePoolsRoute: ExplorePoolsRoute,
  ExploreTokensRoute: ExploreTokensRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface FarmRouteChildren {
  FarmCreateRoute: typeof FarmCreateRoute
  FarmIndexRoute: typeof FarmIndexRoute
}

const FarmRouteChildren: FarmRouteChildren = {
  FarmCreateRoute: FarmCreateRoute,
  FarmIndexRoute: FarmIndexRoute,
}

const FarmRouteWithChildren = FarmRoute._addFileChildren(FarmRouteChildren)

interface PositionsRouteChildren {
  PositionsCreateRoute: typeof PositionsCreateRoute
  PositionsIndexRoute: typeof PositionsIndexRoute
}

const PositionsRouteChildren: PositionsRouteChildren = {
  PositionsCreateRoute: PositionsCreateRoute,
  PositionsIndexRoute: PositionsIndexRoute,
}

const PositionsRouteWithChildren = PositionsRoute._addFileChildren(
  PositionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoinpaperRoute: CoinpaperRoute,
  CultRoute: CultRoute,
  EnsRoute: EnsRoute,
  ExploreRoute: ExploreRouteWithChildren,
  FarmRoute: FarmRouteWithChildren,
  LaunchRoute: LaunchRoute,
  LimitRoute: LimitRoute,
  OneshotRoute: OneshotRoute,
  PositionsRoute: PositionsRouteWithChildren,
  SendRoute: SendRoute,
  SwapRoute: SwapRoute,
  UserRoute: UserRoute,
  WlfiRoute: WlfiRoute,
  CCoinIdRoute: CCoinIdRoute,
  UUserIdRoute: UUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
