/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SendRouteImport } from './routes/send'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CoinpaperRouteImport } from './routes/coinpaper'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as CCoinIdRouteImport } from './routes/c.$coinId'

const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinpaperRoute = CoinpaperRouteImport.update({
  id: '/coinpaper',
  path: '/coinpaper',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const CCoinIdRoute = CCoinIdRouteImport.update({
  id: '/c/$coinId',
  path: '/c/$coinId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coinpaper': typeof CoinpaperRoute
  '/explore': typeof ExploreRoute
  '/landing': typeof LandingRoute
  '/launch': typeof LaunchRoute
  '/orders': typeof OrdersRoute
  '/send': typeof SendRoute
  '/swap': typeof SwapRoute
  '/c/$coinId': typeof CCoinIdRoute
  '/u/$userId': typeof UUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coinpaper': typeof CoinpaperRoute
  '/explore': typeof ExploreRoute
  '/landing': typeof LandingRoute
  '/launch': typeof LaunchRoute
  '/orders': typeof OrdersRoute
  '/send': typeof SendRoute
  '/swap': typeof SwapRoute
  '/c/$coinId': typeof CCoinIdRoute
  '/u/$userId': typeof UUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coinpaper': typeof CoinpaperRoute
  '/explore': typeof ExploreRoute
  '/landing': typeof LandingRoute
  '/launch': typeof LaunchRoute
  '/orders': typeof OrdersRoute
  '/send': typeof SendRoute
  '/swap': typeof SwapRoute
  '/c/$coinId': typeof CCoinIdRoute
  '/u/$userId': typeof UUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coinpaper'
    | '/explore'
    | '/landing'
    | '/launch'
    | '/orders'
    | '/send'
    | '/swap'
    | '/c/$coinId'
    | '/u/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coinpaper'
    | '/explore'
    | '/landing'
    | '/launch'
    | '/orders'
    | '/send'
    | '/swap'
    | '/c/$coinId'
    | '/u/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coinpaper'
    | '/explore'
    | '/landing'
    | '/launch'
    | '/orders'
    | '/send'
    | '/swap'
    | '/c/$coinId'
    | '/u/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoinpaperRoute: typeof CoinpaperRoute
  ExploreRoute: typeof ExploreRoute
  LandingRoute: typeof LandingRoute
  LaunchRoute: typeof LaunchRoute
  OrdersRoute: typeof OrdersRoute
  SendRoute: typeof SendRoute
  SwapRoute: typeof SwapRoute
  CCoinIdRoute: typeof CCoinIdRoute
  UUserIdRoute: typeof UUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coinpaper': {
      id: '/coinpaper'
      path: '/coinpaper'
      fullPath: '/coinpaper'
      preLoaderRoute: typeof CoinpaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$coinId': {
      id: '/c/$coinId'
      path: '/c/$coinId'
      fullPath: '/c/$coinId'
      preLoaderRoute: typeof CCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoinpaperRoute: CoinpaperRoute,
  ExploreRoute: ExploreRoute,
  LandingRoute: LandingRoute,
  LaunchRoute: LaunchRoute,
  OrdersRoute: OrdersRoute,
  SendRoute: SendRoute,
  SwapRoute: SwapRoute,
  CCoinIdRoute: CCoinIdRoute,
  UUserIdRoute: UUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()