/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExploreImport } from './routes/explore'
import { Route as CreateImport } from './routes/create'
import { Route as CoinpaperImport } from './routes/coinpaper'
import { Route as IndexImport } from './routes/index'
import { Route as CCoinIdImport } from './routes/c.$coinId'

// Create/Update Routes

const ExploreRoute = ExploreImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRoute,
} as any)

const CreateRoute = CreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const CoinpaperRoute = CoinpaperImport.update({
  id: '/coinpaper',
  path: '/coinpaper',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CCoinIdRoute = CCoinIdImport.update({
  id: '/c/$coinId',
  path: '/c/$coinId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/coinpaper': {
      id: '/coinpaper'
      path: '/coinpaper'
      fullPath: '/coinpaper'
      preLoaderRoute: typeof CoinpaperImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateImport
      parentRoute: typeof rootRoute
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreImport
      parentRoute: typeof rootRoute
    }
    '/c/$coinId': {
      id: '/c/$coinId'
      path: '/c/$coinId'
      fullPath: '/c/$coinId'
      preLoaderRoute: typeof CCoinIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coinpaper': typeof CoinpaperRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/c/$coinId': typeof CCoinIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coinpaper': typeof CoinpaperRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/c/$coinId': typeof CCoinIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/coinpaper': typeof CoinpaperRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/c/$coinId': typeof CCoinIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coinpaper' | '/create' | '/explore' | '/c/$coinId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coinpaper' | '/create' | '/explore' | '/c/$coinId'
  id: '__root__' | '/' | '/coinpaper' | '/create' | '/explore' | '/c/$coinId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoinpaperRoute: typeof CoinpaperRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  CCoinIdRoute: typeof CCoinIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoinpaperRoute: CoinpaperRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  CCoinIdRoute: CCoinIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/coinpaper",
        "/create",
        "/explore",
        "/c/$coinId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/coinpaper": {
      "filePath": "coinpaper.tsx"
    },
    "/create": {
      "filePath": "create.tsx"
    },
    "/explore": {
      "filePath": "explore.tsx"
    },
    "/c/$coinId": {
      "filePath": "c.$coinId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
